services:
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    environment:
      - DB_TYPE=postgres
      - DB_HOST=gitea_db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - GITEA__server__SSH_PORT=2222
    restart: always
    volumes:
      - git_data:/data
    ports:
      - 2222:2222
    networks:
      - nginx_internal
      - gitea_internal
    expose:
      - 3000
  db:
    image: postgres:alpine
    container_name: gitea_db
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    restart: always
    networks:
      - gitea_internal
    volumes:
      - git_db_data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  git_db_data:
    external: true
  git_data:
    external: true

networks:
  nginx_internal:
    external: true
  gitea_internal:
    external: false